database:
  driver: "sqlite"
  dbname: "passwall"
  username: "user"
  password: "password"
  path: "./store/passwall.db"

# Uncomment for mysql
# database:
#   driver: "mysql"
#   dbname: "passwall"
#   username: "user"
#   password: "password"
#   host: "localhost" # or compose service name
#   port: "3306"

# Uncomment for postgres
# database:
#   driver: "postgres"
#   dbname: "passwall"
#   username: "user"
#   password: "password"
#   host: "localhost" # or compose service name
#   port: "5432"

server:
  port: "3625"
  username: "passwall"
  password: "password"
  passphrase: "passphrase-for-encrypting-passwords-do-not-forget"
  secret: "secret-key-for-JWT-TOKEN"
  timeout: 24 # Token duration in hours format
  generatedPasswordLength: 16 # Minimum 4
  accessTokenExpireDuration: "50m"  # Example: 29m, 2h, 9d
  refreshTokenExpireDuration: "25d"  # Example: 57m, 5h, 7d

backup:
  folder: "./store" # you can feel free to change any where your in project 
  rotation: 7 # backup rotation
  period: "24h" # backup period. Example: 12h, 3h15m, 8h20m30s